
import { group } from "console"
import {
  X,
  Copy,
  ChevronLeft,
  ChevronRight,
  Pause,
  ChevronFirst,
  FolderSync,
  FileInput,
  BrainCircuit,
  ChartSpline,
  Blocks,
  BookType,
  Instagram,
  Linkedin,
  Facebook,
  Menu,
  Building2,
  UserPlus,
  Handshake,
  Building,
  Group,
  Users,
  CircleHelp
} from "lucide-react"

export const Icons = {
  close: X,
  copy: Copy,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  pause: Pause,
  chevronFirst: ChevronFirst,
  folderSync: FolderSync,
  fileInput: FileInput,
  brainCircuit: BrainCircuit,
  chartSpline: ChartSpline,
  blocks:Blocks,
  bookType: BookType,
  instagram:Instagram,
  linkedin: Linkedin,
  facebook:Facebook,
  menu:Menu,
  building2: Building2,
  userPlus: UserPlus,
  handShake:Handshake,
  building:Building,
  group: Group,
  users: Users,
  circleHelp: CircleHelp
}